version: "3.9"
name: bd-mysql

services:
  bd-mysql:
    container_name: bd-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clave_root
      MYSQL_DATABASE: CHARLA
      MYSQL_USER: admin
      MYSQL_PASSWORD: clave_admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network-public

networks:
  network-public:
    driver: bridge

volumes:
  mysql-data:
    driver: local