version: "3.9"
name: bd-mysql

networks:
  network-public:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  bd-mysql:
    container_name: bd-mysql
    image: mysql:8.0
    restart: always
    env_file: 
      mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
      - /c/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - network-public

  flask-app:
    build: .
    container_name: flask-app
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - bd-mysql
    networks:
      - network-public